name: Azure WSL repo clone
description: "Clones your repo into WSL."

inputs:
  distro:
    description: Which (installed) distro to use. Use the name as shown in 'wsl -l -v'.
    required: true
  working-dir:
    description: Where the repo should be cloned
    required: false
    default: "."
  submodules:
    description: Whether to fetch submodules or not
    required: false
    default: "false"
  token:
    description: GitHub access token used to fetch the repository. This is required for checking out private repositories. The token will persist in the git config of the checked out repository and is not cleaned up automatically.
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Clone repo
      uses: ubuntu/WSL/.github/actions/wsl-bash@main
      with:
        distro: ${{ inputs.distro }}
        exec: |
          set -eu

          export GIT_TERMINAL_PROMPT=0

          mkdir -p ${{ inputs.working-dir }}

          CLONE_URL="https://github.com/${{ github.repository }}.git"
          if [ -n "${{ inputs.token }}" ] ; then
              CLONE_URL="https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git"
          fi
          git clone --quiet --depth 1 "$CLONE_URL" ${{ inputs.working-dir }}

          cd ${{ inputs.working-dir }}
          git fetch --quiet --depth 1 --no-tags --prune --update-head-ok origin +${{ github.sha }}:${{ github.ref }}
          git checkout --quiet ${{ github.sha }}

          if [ "${{ inputs.submodules }}" = true ] ; then
              git submodule --quiet update --init --recursive --depth 1
          fi
