name: Example action using WSL

concurrency: azure-vm

on:
  pull_request:
    paths:
      # We run it when changing one if its dependencies
      - .github/workflows/wsl-example.yaml
      - .github/actions/**
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install or update WSL
        uses: ./.github/actions/wsl-install
        with:
          distro: Ubuntu

      - name: Checkout your repo into WSL
        uses: ./.github/actions/wsl-checkout
        with:
          distro: Ubuntu
          working-dir: '~/myrepo'

      # You'll probably use this action if you program runs entirely inside WSL
      - name: Run bash inside WSL
        uses: ./.github/actions/wsl-bash
        with:
          distro: Ubuntu
          working-dir: '~/myrepo'
          exec: |
            echo "Hello from $(lsb_release -ds)"

      - name: Run powershell on Windows
        shell: powershell
        env:
          WSL_UTF8: '1' # Recommended otherwise it's hard to read on Github
        run: wsl --list --verbose
